### ISSUE TITLE
Remove password restrictions for login 

### ISSUE THREAD

**Issue by marahml** [DoSomething/LetsDoThis-iOS#897] opened 2016-03-02 17:37 UTC
Users can currently reset their DS password online without any character limitations - but cannot login with passwords less than 6 characters. 

Let's let the user innnnnnnn.

(Let me know if you need more detail)

**Comment by aaronschachter** [comment] 2016-03-02 17:40
This is now available in 1.0.7 - duplicate of #892

**Closed by aaronschachter** 2016-03-02 17:40 UTC
Labels: blocker
